HealthNet/urls.py
"""
HealthNet URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Route to the admin panel
    url(r'^admin/', include(admin.site.urls)),

    # Have the root URL route to the profiles app URLs
    url(r'^', include('profiles.urls')),

    # Have /appointments route to the appointments app URLs
    url(r'^appointments/', include('appointments.urls')),

    # Have /log route to the Log app URLs
    url(r'^log/', include('log.urls')),

    url(r'^messaging/', include('messaging.urls')),
]

log/urls.py
"""
HealthNet Log urls
"""

from django.conf.urls import url

from . import views

app_name = 'log'  # namespace

urlpatterns = [

    # The URL to the log form and log view
    url(r'^$', views.logForm, name='logForm'),

    # This URL will delete a log event with the given primary key
    url(r'^(?P<pk>[0-9]+)/delete$', views.logDelete, name='logDelete'),

    # The URL to parse a specific log request
    # url(r'^(?P<query>\w+)$', views.logParse, name='logParse'),

]

profiles/urls.py
"""
HealthNet Profile URLs
"""
from django.conf.urls import url

from . import views

app_name = 'profiles'  # namespace

urlpatterns = [
    # The root URL links to the index view that displays the login page
    url(r'^$', views.index, name='index'),

    # The register URL links to the register view to create a new user
    url(r'^register/$', views.register, name='register'),

    # The login URL links to the login view which authenticates a user with the given form data
    url(r'^login/$', views.login, name='login'),

    # The logout URL links to the login view which simply logs out the current session
    url(r'^logout/$', views.logout, name='logout'),

    # This URL links to the viewProfile view that displays a user's information
    url(r'^profiles/(?P<username>\w*)$', views.viewProfile, name='viewProfile'),

    # This URL links to the uploadPic view which handles the uploading of profile pictures
    url(r'^profiles/(?P<username>\w+)/uploadpicture$', views.uploadPic, name="uploadPic"),
    url(r'^profiles/(?P<username>\w+)/ajaxpicupload$', views.ajaxUploadPic, name="ajaxUploadPic"),

    # This URL is used to update a user's shownTutorial field after the tutorial
    url(r'^profiles/(?P<username>\w+)/endtut$', views.endTut, name="endTut"),

    # This URL is used to show a preview of a user's profile to others
    url(r'^profiles/(?P<username>\w+)/peek$', views.peekView, name='peekView'),

    # This URL is used to receive search terms and return results to the user
    url(r'^profiles/(?P<username>\w+)/search$', views.searchView, name='searchView'),

    # These URLs are used to update basic patient info
    url(r'^profiles/(?P<username>\w+)/editbasicinfo$', views.editBasicInfo, name='editBasicInfo'),
    url(r'^profiles/(?P<username>\w+)/savebasicinfo$', views.saveBasicInfo, name='saveBasicInfo'),

    # These URLs are used to update patient insurance info
    url(r'^profiles/(?P<username>\w+)/editmedicalinfo$', views.editMedicalInfo, name='editMedicalInfo'),
    url(r'^profiles/(?P<username>\w+)/savemedicalinfo$', views.saveMedicalInfo, name='saveMedicalInfo'),

    # These URLs are used to add and edit contacts
    url(r'^profiles/(?P<username>\w+)/addcontact$', views.addContact, name='addContact'),
    url(r'^profiles/(?P<username>\w+)/editcontact/(?P<pk>[0-9]+)$', views.editContact, name='editContact'),

    # This URL links to the deleteContact view which deletes the contact
    url(r'^profiles/(?P<username>\w+)/deletecontact/(?P<pk>[0-9]+)$', views.deleteContact, name='deleteContact'),

    # This is a temporary URL used to test new UI features
    url(r'^ui$', views.uiTest, name="uiTest"),
]

profiles/models.py
"""
HealthNet Profile Models
"""
from django.db import models
from django.contrib.auth.models import User
from profiles.helpers import randomFileName

'''
Hospital model

model of hospital object for doctors, nurses, and patients to be parented by

instance variables:
    name: name of hospital
    street: street string
    city: city string
    state: 2 character state code
    zipcode: string of zipcode
    phoneNumber: hospital phone number
    numVisits: The number of patient visits to this hospital

'''


class Hospital(models.Model):
    name = models.CharField(max_length=64)
    street = models.CharField(max_length=64)
    city = models.CharField(max_length=32)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=10)
    phoneNumber = models.CharField(max_length=10)  # CSIF?
    numVisits = models.IntegerField()

    def __str__(self):
        return self.name


'''
User model

The User model represents the basic information for every Healthnet user.

instance variables:
user: A Django User model for authentication
accountType: THe type of account (patient, doctor, etc.)
isNew: Is this a brand new account that has just been created
shownTutorial: Has the profile tutorial been shown to this user
photo: A profile picture
'''


class HealthNetUser(models.Model):
    ACCOUNT_TYPE_CHOICES = (
        ('P', 'Patient'),
        ('D', 'Doctor'),
        ('A', 'Admin'),
        ('N', 'Nurse'),
    )
    user = models.OneToOneField(User)
    accountType = models.CharField(max_length=1, choices=ACCOUNT_TYPE_CHOICES, default='P')
    isNew = models.BooleanField(default=True)
    shownTutorial = models.BooleanField(default=False)
    photo = models.ImageField(upload_to=randomFileName, default="/static/images/profile.png")

    def __str__(self):
        return self.user.username


#
'''
Patient model

The Patient model is a child of User and contains fields specific to a patient.

instance variables:
birthDate: The patient's date of birth
heightFeet: The feet part of a patient's height
heightInches: The inches part of a patient's height
weight: The patient's weight
insuranceCompany: The patient's insurance company
insuranceId: The patient's insurance ID
hospitalPref: The patient's prefered hospital
hospital: The hospital that the patient is currently at (can be null)
numVisits: The number of hospital visits this patient has had
'''


class Patient(HealthNetUser):
    birthDate = models.DateField()
    heightFeet = models.IntegerField()
    heightInches = models.IntegerField()
    weight = models.IntegerField()
    insuranceCompany = models.CharField(max_length=200)
    insuranceId = models.CharField(max_length=200)
    hospitalPref = models.ForeignKey(Hospital, related_name="hospitalPref")
    hospital = models.ForeignKey(Hospital, related_name="hospital", null=True)
    numVisits = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username


'''
Contact model

The Contact model contains contact information for a person.  Each User has many Contacts.

instance variables:
firstName: A contact's first name
middleInitial: A contact's middle initial
lastName: A contact's last name
phoneNumber: A contact's phone number
street: The street address at which the contact lives
city: The city in which the contact lives
state: The state in which the contact lives
zipcode: The zipcode of the area that the contact lives
relation: The user's relation to this contact
type: The type of contact this is (patient, doctor, emergency, etc.)
user: The user that this contact belongs to
'''


class Contact(models.Model):
    firstName = models.CharField(max_length=32)
    middleInitial = models.CharField(max_length=1, null=True, blank=True)
    lastName = models.CharField(max_length=64)
    phoneNumber = models.CharField(max_length=14)
    street = models.CharField(max_length=64)
    city = models.CharField(max_length=32)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=10)
    RELATION_CHOICES = (
        ('ga', 'Guardian'),
        ('sp', 'Spouse'),
        ('fa', 'Father'),
        ('mo', 'Mother'),
        ('si', 'Sibling'),
        ('ch', 'Child'),
        ('ot', 'Other'),
        ('se', 'Self'),
    )
    relation = models.CharField(max_length=2, choices=RELATION_CHOICES)
    TYPE_CHOICES = (
        ('e', 'Emergency'),
        ('d', 'Doctor'),
        ('n', 'Nurse'),
        ('p', 'Patient'),
    )
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    user = models.ForeignKey(HealthNetUser)

    def __str__(self):
        return self.firstName

'''
Staff model

The Staff model is a child of HealthNetUser.  Any staff using the system
(doctor, nurse, admin) has a staff object associated with them.

instance variables:
hospital: The hospital that the staff member is currently working at
bio: A short biography describing the staff member
'''

class Staff(HealthNetUser):
    hospital = models.ForeignKey(Hospital)
    bio = models.TextField(null=True)

profiles/templates/profiles/ajax_basicinfo.html
<div id="basic-info-content">
  <h3>Phone Number</h3>
  <div class="profile-info-spacing">
    <div class="field-icon fa fa-phone"></div>
    <p class="profile-info"> {{ thiscontact.phoneNumber }} </p>
  </div>
  <h3>Date of Birth</h3>
  <div class="profile-info-spacing">
    <div class="field-icon fa fa-calendar"></div>
    <p class="profile-info">{{ hnuser.birthDate }} </p>
  </div>
  <h3>Height</h3>
  <div class="profile-info-spacing">
    <div class="field-icon fa fa-arrow-up"></div>
    <p class="profile-info">{{ hnuser.heightFeet }}', {{ hnuser.heightInches }}"</p>
  </div>
  <h3>Weight</h3>
  <div class="profile-info-spacing">
    <div class="field-icon fa fa-balance-scale"></div>
    <p class="profile-info">{{ hnuser.weight }} </p>
  </div>
  <h3>Address</h3>
  <div class="profile-address-spacing rcorner-top-right rcorners-left-6">
    <div class="address-field-icon fa fa-map-marker rcorner-top-left" style="color: #D22121;"></div>
    <p class="profile-info">{{ thiscontact.street }}</p>
  </div>
  <div class="profile-address-spacing rcorners-left-6">
    <div class="address-field-icon fa fa-map-marker"></div>
    <p class="profile-info">{{ thiscontact.city }}, {{ thiscontact.state }}</p>
  </div>
  <div class="profile-address-spacing rcorner-bottom-right rcorners-left-6">
    <div class="address-field-icon fa fa-globe rcorner-bottom-left" style="color: #D22121;"></div>
    <p class="profile-info">{{ thiscontact.zipcode }}</p>
  </div>
</div>

profiles/templates/profiles/ajax_profilepicture.html
<img src="{{ hnuser.photo.url }}" id="profile-pic-pic">

profiles/templates/profiles/module_calendar_toolbar.html
<div class="profile-pane hide" id="cal-tools">
  <div class="info-bubble animate-from-bottom" style="padding: 2px; padding-top: 4px; padding-bottom: 4px;">
    <div id="calendar-toolbar">
      <a href="javascript:;" id="create-appointment-button" username="{{ hnuser.user.username }}"
      class="jpop center" popup="create-appointment-popup">
        <div class="profile-quick-link-button" id="create-appointment-btn">
          <i class="fa fa-plus"></i><p>Create Appointment</p>
        </div>
      </a>
    </div>
  </div>
</div>

profiles/templates/profiles/module_contacts.html
<div class="hide" id="contacts-content">
  <div style="height: 20%;"></div>
  <div class="center">
      {% if error_message %}
          <h2 class="text-center" style="color: #ffffff; text-align: center;">{{ error_message }}</h2>
      {% endif %}

      {% if messages %}
          {% for message in messages %}
              <h2 class="text-center scale-0 fade-grow-in"
                  style="color: #ffffff; text-align: center;">{{ message }}</h2>
          {% endfor %}
      {% endif %}
  </div>

  <!-- Contacts Content -->
  <div class="container">
      <div id="contacts-content-inner" class="info-bubble">
          <h1 class="text-center">Contacts</h1>

          <div class="sep-dashed-grey"></div>
          <div id="contact-list" class="contact-list">
              <ul>
                  <li class="view-contact-header">
                      <div class="col-sm-10">
                          <div class="row">
                              <div class="col-sm-2">
                                  First Name
                              </div>
                              <div class="col-sm-1">
                                  M.I.
                              </div>
                              <div class="col-sm-3">
                                  Last Name
                              </div>
                              <div class="col-sm-3">
                                  Phone #
                              </div>
                              <div class="col-sm-2">
                                  Relation
                              </div>
                          </div>
                      </div>
                  </li>
                  <li class="view-contact-header">
                      <div class="col-sm-10">
                          <div class="row">
                              <div class="col-sm-2">
                              </div>
                              <div class="col-sm-1">
                              </div>
                              <div class="col-sm-2">
                              </div>
                              <div class="col-sm-2">
                              </div>
                              <div class="col-sm-2">
                              </div>
                              <div class="col-sm-3">
                              </div>
                          </div>
                      </div>
                  </li>
                  <li class="view-contact-header">
                      <div class="col-sm-10">
                          <div class="row">
                              <div class="col-sm-2">
                              </div>
                              <div class="col-sm-1">
                              </div>
                              <div class="col-sm-2">
                              </div>
                              <div class="col-sm-2">
                              </div>
                              <div class="col-sm-2">
                              </div>
                              <div class="col-sm-3">
                              </div>
                          </div>
                      </div>
                  </li>
                  <br>
                  {% if contacts %}
                      {% for contact in contacts %}

                          <li class="view-contact-item">
                              <div class="row">
                                  <div class="col-sm-10">
                                      <div class="row">
                                          <div class="col-sm-2 contact-list-field">
                                              {{ contact.firstName }}
                                          </div>
                                          <div class="col-sm-1 contact-list-field">
                                              {{ contact.middleInitial }}
                                          </div>
                                          <div class="col-sm-3 contact-list-field">
                                              {{ contact.lastName }}
                                          </div>
                                          <div class="col-sm-3 contact-list-field">
                                              {{ contact.phoneNumber }}
                                          </div>
                                          <div class="col-sm-2 contact-list-field">
                                              {{ contact.get_relation_display }}
                                          </div>
                                      </div>
                                      <div class="sep-solid-grey" style=""></div>
                                      <div class="row">
                                          <div class="col-sm-10 contact-list-field">
                                              {{ contact.street }} {{ contact.city }}, {{ contact.state }}, {{ contact.zipcode }}
                                          </div>
                                      </div>
                                  </div>
                                  <div class="col-sm-2 contact-list-field">
                                      <a href="javascript:;" popup="edit-contact-popup" username="{{ hnuser.user.username }}"
                                         class="contact-list-edit-button jpop" contactid="{{ contact.id }}">Edit</a>
                                      <a href="javascript:;" username="{{ hnuser.user.username }}" popup="delete-contact-confirm-popup"
                                      contactid="{{ contact.id }}" class="contact-list-delete-button jpop">Delete</a>
                                  </div>
                                  <div id="contact-delete-info" username="" contactid=""></div>
                              </div>
                          </li>

                      {% endfor %}
                  {% else %}
                      <li class="view-contact-item">
                          <div class="row">
                              <div class="col-sm-12 contact-list-field">
                                  You have no contacts
                              </div>
                          </div>
                      </li>
                  {% endif %}
              </ul>
          </div>

          <div class="center text-center edit-submit">
              <a href="javascript:;">
                  <input type="submit" id="add-contact-button"
                  class="add-contact-button button-gradient-red jpop" popup="add-contact-popup" value="Add Contact">
              </a>
          </div>

      </div>
  </div>
</div>
<!-- End content -->

<!-- Add Contact JPop -->
<div class="edit-form" id="add-contact-popup" width="50%" height="90%" style="display: none;" jpoptitle="Add Contact">
  <div class="edit-form-inner">
    <form id="add-contact-form" class="center" action="/profiles/ajax/addcontact" method="post">
      {% csrf_token %}
      <div id="add-contact-form-content"></div>
      <div class="edit-submit">
        <input id="add-contact-submit" type="submit" value="Add" class="button-gradient-red submit-btn">
      </div>
    </form>
  </div>
</div>
<!-- End Add Contact JPop -->

<!-- Edit Contact JPop -->
<div class="edit-form" id="edit-contact-popup" width="50%" height="90%" style="display: none;" jpoptitle="Edit Contact">
  <div class="edit-form-inner">
    <form id="edit-contact-form" class="center" action="/profiles/{{ hnuser.user.username }}/editcontact" method="post">
      {% csrf_token %}
      <div id="edit-contact-form-content"></div>
      <div class="edit-submit">
        <input id="edit-contact-submit" type="submit" value="Save" class="button-gradient-red submit-btn">
      </div>
    </form>
  </div>
</div>
<!-- End Edit Contact JPop -->

<!-- Delete Confirm JPop -->
<div class="edit-form" id="delete-contact-confirm-popup" width="50%" style="display: none;">
  <div class="edit-form-inner">
    <h2>Are you sure you want to delete this contact?</h2>
    <form class="center" action="" method="post">
      <div class="edit-submit">
        <a href="javascript:;" id="delete-contact-yes">
          <input type="submit" class="button-gradient-red" value="Yes">
        </a>
        <a style="margin-left: 10px;" href="javascript:;" id="delete-contact-no">
          <input type="submit" class="button-gradient-red" value="No">
        </a>
      </div>
    </form>
  </div>
</div>
<!-- End Delete Confirm JPop -->

profiles/templates/profiles/module_day_calendar.html
<div class="profile-pane hide" id="cal2-id">
  <div class="info-bubble animate-from-bottom">
    <div id="daycalendar">
      <div id="calendar2"></div>
    </div>
  </div>
</div>

<script>
$(document).ready(function () {
  var ar = {{json_ar|safe}};

  var sy = ar[0];
  var sm = ar[1];
  var sd = ar[2];
  var sh = ar[3];
  var sn = ar[4];
  var ey = ar[5];
  var em = ar[6];
  var ed = ar[7];
  var eh = ar[8];
  var en = ar[9];
  var id = ar[10];
  var title = ar[11];
  var rsn = ar[12];

  var hite = $(window).height()-160;
  var dayHite = $(window).height()-238;

  var eventArray = [];
  for (var key in sy) {
     var endhour = eh[key];
     var endmin = en[key];
     var starthour = sh[key];
     var startmin = sn[key];
     var event = {
         id: id[key],
         title: title[key],
         description: rsn[key],
         start: new Date(sy[key], sm[key] - 1, sd[key], starthour, startmin),
         end: new Date(ey[key], em[key] - 1, ed[key], endhour, endmin)
     };
     eventArray.push(event);
  }

  $('#calendar2').fullCalendar({
      theme: false,

      header: {
          left: 'title',
          center: '',
          right: 'today'

      },

      titleFormat: 'MMM D',

      events: eventArray,

      eventRender: function (event, element) {
          element.qtip({
              content: event.description,
              style: {
                  classes: 'qtip-light qtip-shadow',
                  tip: {
                      offset: 155
                  }
              }
          });
      },

      defaultView: 'agendaDay',

      height: dayHite,

      eventClick: function (calEvent, jsEvent, view) {

          $("#view-appointment-clicker").click();

          var token = $('input[name=\"csrfmiddlewaretoken\"]');
          $.ajax({
              url: "/appointments/{{ hnuser.user.username }}/" + calEvent.id,
              type: "POST",
              data: {
                  client_response: "",
                  csrfmiddlewaretoken: token.val()
              },
              success: function (data) {
                $('#view-appointment-content').html(data.html);
                $('#view-appointment-content').append("<input id=\"appointmentpk\" type=\"hidden\" pk=\"" +
                calEvent.id + "\" username=\"{{ hnuser.user.username }}\">");
                setupChangeAppointmentScripts();
                initSpecificJPop(document.getElementById('delete-appointment-button'));
              },
              error: function (jqXHR, textStatus, errorThrown) {

              }
          });
      }
  })
});
</script>

profiles/templates/profiles/peek_doctor.html
<div class="col-sm-4 col-sm-push-8">
  <!-- Profile Picture -->
  {% include "profiles/module_staff_picture.html" %}
  <!-- End Profile Picture -->
</div>
<div class="col-sm-8 col-sm-pull-4">
  <div class="row center" id="doctor-peek-links">
    <div class="col-sm-12 width-auto">
      <div class="profile-pane width-auto">
        <div class="info-bubble center scale-0 fade-grow-in width-auto" id="doctor-peek-links-bubble">
          <div class="profile-quick-link-button doctor-peek-button">
            <i class="fa fa-comment"></i>
            <p id="doctor-peek-message-link">Send Message</p>
          </div>
          <div class="profile-quick-link-button doctor-peek-button">
            <i class="fa fa-calendar"></i>
            <p id="doctor-peek-appointment-link">Schedule Appointment</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="profile-pane">
    <div class="info-bubble center scale-0 fade-grow-in">
      <h1>Bio</h1>
      <div class="sep-solid-grey" style="width: 100%;"></div>
      <p>{{hnuser.bio}}</p>
    </div>
  </div>
</div>

profiles/templates/profiles/peek_patient.html
<div id="peek-username" username="{{hnuser.user.username}}"></div>
<div class="col-sm-4 col-sm-push-8">
  <!-- Profile Picture -->
  <div id="patient-peek-picture">
  {% include "profiles/module_profile_picture.html" %}
  </div>
  <!-- End Profile Picture -->
</div>
<div class="col-sm-8 col-sm-pull-4">
  <!-- Profile Picture -->
  {% include "profiles/module_patient_peek_tabbed.html" %}
  <!-- End Profile Picture -->
</div>

profiles/templates/profiles/profile_admin.html
<!--
  adminprofile.html
  ==============================================================================

  This template shows a admin's profile.
 -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Include the global CSS, JS, etc. links -->
    {% include "includes/headlinks.html" %}

    <title>HealthNet - {{ hnuser.user.username }}</title>
</head>

<body id="profile-body">

<!-- Include the global page header -->
{% include "includes/header.html" %}

<!-- Include the page sidebar -->
{% include "includes/sidebar.html" %}

<!-- This is where the unique content for each page goes -->
<div class="content">

  <!-- Patient Profile Content -->
  <div class="container profile-content">
    <h1>Admin</h1>
  </div>
  <!-- End Profile Content -->

</div>
<!-- End content -->

<!-- General Document Script -->
<script>
document.getElementById('profile-body').style.overflow = "auto";
</script>

</body>

</html>

profiles/templates/profiles/sidebartest.html
<html>

<head>
    <!-- Include the global CSS, JS, etc. links -->
    {% include "includes/headlinks.html" %}

    <title></title>
</head>

<body style="background-color: #A81E1E">

<!-- Include the global page header -->
{% include "includes/header.html" %}

<!-- This is where the unique content for each page goes -->
<div class="content">
    {% include "includes/sidebar.html" %}
</div>
<!-- End content -->

<script>

</script>
</body>

</html>

profiles/templates/profiles/temp_ajaxtest.html
<h1>Patient:</h1>
<h2>{{patientContact.firstName}} {{patientContact.middleInitial}} {{patientContact.lastName}}</h2>

profiles/templates/profiles/viewcontacts.html
<!--
  viewcontacts.html
  ==============================================================================

  This shows a list of the user's contacts.
 -->

<html>

  <head>
    <!-- Include the global CSS, JS, etc. links -->
    {% include "includes/headlinks.html" %}

    <title>{{ hnuser.user.username }} - Contacts</title>
  </head>

  <body id="body">

    <!-- Include the global page header -->
    {% include "includes/header.html" %}

    <!-- Include the sidebar -->
    {% include "includes/sidebar.html" %}

    <!-- This is where the unique content for each page goes -->
    <div class="content">

      <div class="center">
          {% if error_message %}
              <h2 class="text-center" style="color: #ffffff; text-align: center;">{{ error_message }}</h2>
          {% endif %}

          {% if messages %}
              {% for message in messages %}
                  <h2 class="text-center scale-0 fade-grow-in"
                      style="color: #ffffff; text-align: center;">{{ message }}</h2>
              {% endfor %}
          {% endif %}
      </div>

      <!-- Contacts Content -->
      <div class="container" id="contacts-content">
        <div id="contacts-content-inner" class="bg-color-white rcorners-10">
          <h1 class="text-center">Contacts</h1>
          <div class="sep-dashed-grey"></div>
          <div class="contact-list">
          <ul>
            <li class="view-contact-header">
              <div class="row">
                <div class="col-sm-2">
                  First Name
                </div>
                <div class="col-sm-1">
                  M.I.
                </div>
                <div class="col-sm-2">
                  Last Name
                </div>
                <div class="col-sm-2">
                  Phone #
                </div>
                <div class="col-sm-2">
                  Relation
                </div>
                <div class="col-sm-3">
                </div>
              </div>
            </li>
            <br>
          {% if contacts %}
          {% for contact in contacts %}

          <li class="view-contact-item">
            <div class="row">
              <div class="col-sm-10">
                <div class="row">
                  <div class="col-sm-2 contact-list-field">
                    {{ contact.firstName }}
                  </div>
                  <div class="col-sm-1 contact-list-field">
                    {{ contact.middleInitial }}
                  </div>
                  <div class="col-sm-2 contact-list-field">
                    {{ contact.lastName }}
                  </div>
                  <div class="col-sm-2 contact-list-field">
                    {{ contact.phoneNumber }}
                  </div>
                  <div class="col-sm-2 contact-list-field">
                    {{ contact.get_relation_display }}
                  </div>
                  <div class="col-sm-3 contact-list-field">

                  </div>
                </div>
                <div class="sep-solid-grey" style=""></div>
                <div class="row">
                  <div class="col-sm-12 contact-list-field">
                    {{ contact.street }} {{ contact.city }}, {{ contact.state }}, {{ contact.zipCode }}
                  </div>
                </div>
              </div>
              <div class="col-sm-2 contact-list-field">
                <a href="/profiles/{{ hnuser.user.username }}/editcontact/{{ contact.id }}" class="contact-list-edit-button">Edit</a>
                <a href="/profiles/{{ hnuser.user.username }}/deletecontact/{{ contact.id }}" class="contact-list-delete-button">Delete</a>
              </div>
            </div>
          </li>

          {% endfor %}
          {% else %}
          <li class="view-contact-item">
            <div class="row">
              <div class="col-sm-12 contact-list-field">
                You have no contacts
              </div>
            </div>
          </li>
          {% endif %}
          </ul>
          </div>

        </div>

        <div class="center text-center edit-submit">
          <a href="/profiles/{{ hnuser.user.username }}/addcontact">
              <input type="submit" class="add-contact-button button-gradient-red" value="Add Contact">
          </a>
        </div>
      </div>
    </div>
    <!-- End content -->

    <script>
    document.getElementById('body').style.overflow = "auto";
    // $("#body").animate({
    //     width: "100%"
    // }, 1000, function () {
    //     document.getElementById('body').style.overflow = "auto";
    // });
    </script>

  </body>

</html>